logging:
  level:
    ru.otus.spring.kushchenko: INFO
    org.springframework: WARN
  file: logs/app.log
  pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n'

spring:
  cache:
    cache-names: questions
    caffeine:
      spec: initialCapacity = 10, maximumSize = 150, expireAfterWrite = 10m

locale: ru
questionSource: classpath:data/questions_ru.csv
